name: compile

on: [push, pull_request]

jobs:
  compile-examples:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: arduino/compile-sketches@main
      with:
        fqbn: 'arduino:avr:uno'
        libraries: |
          - source-path: ./
          - name: Adafruit BusIO
          - name: Adafruit SSD1306
          - name: Adafruit GFX Library