name: unittest

on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install requirements
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: |
          bundle exec arduino_ci.rb --skip-examples-compilation